language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
env:
  global:
  - secure: C4a5YMuaXrqrwZfV4VoHOhO1+VH58ApPcpQJi7arfbK6wnXyNfFtWxJ5AFVgM+kPztkUokrZ1KnhdHTYScP/wX7oN2JR7oqwP28NePcN2DzN69DwhcMAjeiEwD1r1ZyCgiblAgcyv20qQzH5Y0B9wFaA73+ZAGXg90gGR6r9s1dae9P5nvLxwpLLdVokn5PMidkMlY3HzRvD6woZ4YS/4vb2xkMBADt02lEUd9tWf7hDJx1ps3fxAe9wUWf8sSASJERG0L9x0r0RXx70NA/TOLkk46JiKu+LtGhuFVnSXGGVlI0HHsEbV4TVhVGwyZ9anyEBjiKue67VHRHTDdr5z5lL2Afv9Ibfx50cywc8ughr/jzp7a+ZCDm932R9JxgKUIsS67p+jvRr8IBNiwsNZ4yJdhgYsZPbSccT1NVJm7pDa/9nHOtEDjO9mvui3o2utEVoCav/JuPpcgZITG7BLHlaFyH/ckvCpY+ngBhrxv2/KoAfxx/NVqDhIbknnICses9sb7vRC4jY8IVIcDiHNplhvk/YJ9gBaBvkTL3upkzKISRWB7Ybh3TKlJgLAsB6YITiBBJ9WAA3WVmwOuX1Cjlz3iRrHNC12n/I+yTKEnTOWrPfkHb/jniZmCh6sT/mPZSwj/j2laxHRGv7UG/17AqevPNIyafK9YXxdjKV884=
  - secure: FupMrnkODwYkNsRhKJPItRa60u/7i+URRA2XXPtjA7kesT4ZpkD6ewL7a58vZhHkWCWLXVXQBr3Jg41J5bR0ELkMUJuknqRp2N80SIii8nhK38VWgK9sEx+6ysaQtVNHPt1qEtYmwP2Jw+wY0VZBRRU0/G51fjVLcdEs2vnj92LaDw3Rp82QNj4iPNC2j/k8ZcYyzJHqXn+0T2N0iJdwL7wdusN4K5uCp5S6EWAp8Hnh9G5Zkfy8Xs/XEOtjTC6F/7IdWKB4C829gi+dT13ORk9FYuopwS1OKYNQ9/DoQWQ9CmBT6FHJEU0ohU5quEjOWLL6asM7u0iNnp6jqqTAs0QvPXBU4Go1mFHDHjxbUjxtlVz124ajz+X7Xo68G9ZQ/jrzKFSSOkXsjovZVrDqd54vy3Ih/4ffzAaDmwa8oJZUROqVpD0f37ByMeSB6oPC2EgHZBCcDuD2JkzTqsBrjhPuwOJnK3qOyrH7yGyulBu/H4O0VA3vocxyI0BNIYh2dzBDjrhUVTF2L67dHeksgEsFdNP3QyNWE0AI4yYGvqE/drcHXtAcdAll2IFedbNsUNofSE4QjbTeUwQP1t6drlsKNnDddCgZ5gvzriGj0TElZN3rqzjCTAOMbHRys5dUwR5bPBkzQiTZqqUm+2vGNmAkezMRx7g5xdrcA8+BXcI=
script:
  - mvn versioneye:update test